sonar.organization=magenta-mause
sonar.projectKey=cosy-domain-provider-frontend
sonar.projectName=Cosy Domain Provider Frontend
sonar.sources=src
sonar.exclusions=src/api/generated/**,src/routeTree.gen.ts
sonar.javascript.lcov.reportPaths=coverage/lcov.info
