/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as MfaSetupRouteImport } from './routes/mfa-setup'
import { Route as MfaChallengeRouteImport } from './routes/mfa-challenge'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BillingRouteImport } from './routes/billing'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as DomainDomainIdRouteImport } from './routes/domain/$domainId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSubdomainsRouteImport } from './routes/admin/subdomains'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminSubdomainsIndexRouteImport } from './routes/admin/subdomains/index'
import { Route as AdminUsersUserIdRouteImport } from './routes/admin/users/$userId'
import { Route as AdminSubdomainsSubdomainIdRouteImport } from './routes/admin/subdomains/$subdomainId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaSetupRoute = MfaSetupRouteImport.update({
  id: '/mfa-setup',
  path: '/mfa-setup',
  getParentRoute: () => rootRouteImport,
} as any)
const MfaChallengeRoute = MfaChallengeRouteImport.update({
  id: '/mfa-challenge',
  path: '/mfa-challenge',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BillingRoute = BillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any)
const DomainDomainIdRoute = DomainDomainIdRouteImport.update({
  id: '/domain/$domainId',
  path: '/domain/$domainId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSubdomainsRoute = AdminSubdomainsRouteImport.update({
  id: '/subdomains',
  path: '/subdomains',
  getParentRoute: () => AdminRoute,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSubdomainsIndexRoute = AdminSubdomainsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminSubdomainsRoute,
} as any)
const AdminUsersUserIdRoute = AdminUsersUserIdRouteImport.update({
  id: '/$userId',
  path: '/$userId',
  getParentRoute: () => AdminUsersRoute,
} as any)
const AdminSubdomainsSubdomainIdRoute =
  AdminSubdomainsSubdomainIdRouteImport.update({
    id: '/$subdomainId',
    path: '/$subdomainId',
    getParentRoute: () => AdminSubdomainsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/admin/subdomains': typeof AdminSubdomainsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/subdomains/$subdomainId': typeof AdminSubdomainsSubdomainIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/subdomains/': typeof AdminSubdomainsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/subdomains/$subdomainId': typeof AdminSubdomainsSubdomainIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/subdomains': typeof AdminSubdomainsIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/billing': typeof BillingRoute
  '/dashboard': typeof DashboardRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/mfa-challenge': typeof MfaChallengeRoute
  '/mfa-setup': typeof MfaSetupRoute
  '/register': typeof RegisterRoute
  '/reset-password': typeof ResetPasswordRoute
  '/settings': typeof SettingsRoute
  '/verify': typeof VerifyRoute
  '/admin/subdomains': typeof AdminSubdomainsRouteWithChildren
  '/admin/users': typeof AdminUsersRouteWithChildren
  '/domain/$domainId': typeof DomainDomainIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/subdomains/$subdomainId': typeof AdminSubdomainsSubdomainIdRoute
  '/admin/users/$userId': typeof AdminUsersUserIdRoute
  '/admin/subdomains/': typeof AdminSubdomainsIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/mfa-setup'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/verify'
    | '/admin/subdomains'
    | '/admin/users'
    | '/domain/$domainId'
    | '/admin/'
    | '/admin/subdomains/$subdomainId'
    | '/admin/users/$userId'
    | '/admin/subdomains/'
    | '/admin/users/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/billing'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/mfa-setup'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/verify'
    | '/domain/$domainId'
    | '/admin'
    | '/admin/subdomains/$subdomainId'
    | '/admin/users/$userId'
    | '/admin/subdomains'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/billing'
    | '/dashboard'
    | '/forgot-password'
    | '/login'
    | '/mfa-challenge'
    | '/mfa-setup'
    | '/register'
    | '/reset-password'
    | '/settings'
    | '/verify'
    | '/admin/subdomains'
    | '/admin/users'
    | '/domain/$domainId'
    | '/admin/'
    | '/admin/subdomains/$subdomainId'
    | '/admin/users/$userId'
    | '/admin/subdomains/'
    | '/admin/users/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  BillingRoute: typeof BillingRoute
  DashboardRoute: typeof DashboardRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  MfaChallengeRoute: typeof MfaChallengeRoute
  MfaSetupRoute: typeof MfaSetupRoute
  RegisterRoute: typeof RegisterRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SettingsRoute: typeof SettingsRoute
  VerifyRoute: typeof VerifyRoute
  DomainDomainIdRoute: typeof DomainDomainIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-setup': {
      id: '/mfa-setup'
      path: '/mfa-setup'
      fullPath: '/mfa-setup'
      preLoaderRoute: typeof MfaSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mfa-challenge': {
      id: '/mfa-challenge'
      path: '/mfa-challenge'
      fullPath: '/mfa-challenge'
      preLoaderRoute: typeof MfaChallengeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/billing': {
      id: '/billing'
      path: '/billing'
      fullPath: '/billing'
      preLoaderRoute: typeof BillingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/domain/$domainId': {
      id: '/domain/$domainId'
      path: '/domain/$domainId'
      fullPath: '/domain/$domainId'
      preLoaderRoute: typeof DomainDomainIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/subdomains': {
      id: '/admin/subdomains'
      path: '/subdomains'
      fullPath: '/admin/subdomains'
      preLoaderRoute: typeof AdminSubdomainsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/subdomains/': {
      id: '/admin/subdomains/'
      path: '/'
      fullPath: '/admin/subdomains/'
      preLoaderRoute: typeof AdminSubdomainsIndexRouteImport
      parentRoute: typeof AdminSubdomainsRoute
    }
    '/admin/users/$userId': {
      id: '/admin/users/$userId'
      path: '/$userId'
      fullPath: '/admin/users/$userId'
      preLoaderRoute: typeof AdminUsersUserIdRouteImport
      parentRoute: typeof AdminUsersRoute
    }
    '/admin/subdomains/$subdomainId': {
      id: '/admin/subdomains/$subdomainId'
      path: '/$subdomainId'
      fullPath: '/admin/subdomains/$subdomainId'
      preLoaderRoute: typeof AdminSubdomainsSubdomainIdRouteImport
      parentRoute: typeof AdminSubdomainsRoute
    }
  }
}

interface AdminSubdomainsRouteChildren {
  AdminSubdomainsSubdomainIdRoute: typeof AdminSubdomainsSubdomainIdRoute
  AdminSubdomainsIndexRoute: typeof AdminSubdomainsIndexRoute
}

const AdminSubdomainsRouteChildren: AdminSubdomainsRouteChildren = {
  AdminSubdomainsSubdomainIdRoute: AdminSubdomainsSubdomainIdRoute,
  AdminSubdomainsIndexRoute: AdminSubdomainsIndexRoute,
}

const AdminSubdomainsRouteWithChildren = AdminSubdomainsRoute._addFileChildren(
  AdminSubdomainsRouteChildren,
)

interface AdminUsersRouteChildren {
  AdminUsersUserIdRoute: typeof AdminUsersUserIdRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminUsersRouteChildren: AdminUsersRouteChildren = {
  AdminUsersUserIdRoute: AdminUsersUserIdRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminUsersRouteWithChildren = AdminUsersRoute._addFileChildren(
  AdminUsersRouteChildren,
)

interface AdminRouteChildren {
  AdminSubdomainsRoute: typeof AdminSubdomainsRouteWithChildren
  AdminUsersRoute: typeof AdminUsersRouteWithChildren
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminSubdomainsRoute: AdminSubdomainsRouteWithChildren,
  AdminUsersRoute: AdminUsersRouteWithChildren,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  BillingRoute: BillingRoute,
  DashboardRoute: DashboardRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  MfaChallengeRoute: MfaChallengeRoute,
  MfaSetupRoute: MfaSetupRoute,
  RegisterRoute: RegisterRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SettingsRoute: SettingsRoute,
  VerifyRoute: VerifyRoute,
  DomainDomainIdRoute: DomainDomainIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
